auto

diff --git a/bin/shts b/bin/shts
--- a/bin/shts
+++ b/bin/shts
@@ -3,9 +3,13 @@
 set -eu
 shopt -s inherit_errexit
 
-. "${0}.sh"
+name=shts
 
-# Array with Command Executed (variable set by: shts).
+. "${0/bats/${name}}.sh"
+
+bats="$(brew --prefix bats-core)/bin/bats"
+
+# Command Executed (variable set by: shts).
 #
 export SHTS_COMMAND
 
@@ -43,34 +47,40 @@ help() {
   cat <<EOF
 usage: ${script} [<tests>] [<options>]
    or: ${script} -h|-help|commands|help|functions|verbose
-   or: . ${script%.*}.sh
+   or: . ${name}.sh
 
-bats testing wrapper and helper functions when "${script%.*}.sh" sourced
+bats testing wrapper and helper functions when "${name}.sh" sourced
 
-<tests> is the path to a Bats test file, or the path to a directory containing Bats test files (ending with ".bats")
-if no <tests> run for: first directory found with ".bats" files in working directory,
-or either 'tests', 'test' or '__tests__' under top repository path
+<tests> is the path to a Bats test file, or the path to a directory containing Bats
+test files (ending with ".bats" or ".${name}"). If no <tests> run for: first directory found with ".bats"
+files in working directory, or either 'tests', 'test' or '__tests__' under top repository path.
 
 Changes to top repository path \$SHTS_TOP when running testa and top path found, otherwise changes
 to the \$SHTS_TEST_DIR
 
 Commands:
-   -h, --help, help  display this help and exit
-   commands          display ${script}' commands
-   functions         display functions available when ${script} is sourced
-   list              display tests found relative to current working directory
+  -h, --help, help          display this help and exit
+  commands                  display ${script}' commands
+  functions                 display functions available when ${name}.sh is sourced
+  list                      display tests found relative to current working directory
 
 Options:
-   --dry-run         show command that would be executed and globals
-   --one             run only one job in parallel instead of \$BATS_NUMBER_OF_PARALLEL_JOBS
-   --verbose         run bats tests showing all outputs, with trace and not cleaning the tempdir
+  --dry-run                 show command that would be executed and globals
+  --one                     run only one job in parallel instead of \$BATS_NUMBER_OF_PARALLEL_JOBS
+  --verbose                 run bats tests showing all outputs, with trace and not cleaning the tempdir
+
+Bats options:
+$(awk '/--count/,0' < <("${bats}" --help))
 
 Globals:
-   SHTS_COMMAND     Array with Command Executed.
-   SHTS_GATHER      Gather the output of failing *and* passing tests as files in directory [--gather-test-outputs-in].
-   SHTS_OUTPUT      Directory to write report files [-o|--output].
-   SHTS_TEST_DIR    Path to the test directory, passed as argument or found by 'shts'.
-   SHTS_TESTS       Array of tests found.
+   SHTS_COMMAND             Command Executed.
+   SHTS_GATHER              Gather the output of failing *and* passing tests as
+                            files in directory [--gather-test-outputs-in].
+   SHTS_OUTPUT              Directory to write report files [-o|--output].
+   SHTS_TEST_DIR            Path to the test directory, passed as argument or found by '${name}'.
+   SHTS_TESTS               Array of tests found.
+
+$("${bats}" --version)
 EOF
   exit $rc
 }
@@ -116,7 +126,7 @@ directory() {
 #######################################
 main() {
   script="${0##*/}"
-  local outputs; outputs="$(realpath "${SHTS_TOP:-.}/.output")"
+  local outputs; outputs="$(realpath "${SHTS_TOP:-.}/.${0##*/}")"
 
   local directory
   local dry=false
@@ -126,7 +136,7 @@ main() {
   local no_parallelize_across_files=()
   local no_parallelize_within_files=()
   local no_tempdir_cleanup=false
-  local jobs=(-j "${BATS_NUMBER_OF_PARALLEL_JOBS:-400}")
+  local jobs=(--jobs "${BATS_NUMBER_OF_PARALLEL_JOBS:-400}")
   local options=()
   local one=false
   local output=false
@@ -144,9 +154,9 @@ main() {
       --code-quote-style) options+=("$1" "$2"); shift ;;
       -c|--count) options+=("$1") ;;
       -f|--filter) options+=("$1" "$2"); shift ;;
-      -F|--formatter) options+=("$1" "$2"); shift ;;
+      -F|--formatter) options+=("$1" "${2/bashpro/pretty}"); shift ;;
       -d|--dry-run) dry=true ;;
-      -j|--jobs) jobs=(-j "$2"); shift;;
+      -j|--jobs) jobs=("$1" "$2"); shift;;
       --gather-test-outputs-in)
         gather_test_outputs_in=true; gather_dir=("$(realpath "$2")"); options+=("$1" "$2"); shift ;;
       --no-parallelize-across-files) no_parallelize_across_files=("$1") ;;
@@ -171,19 +181,20 @@ main() {
       -*) help "$1" "invalid option" ;;
       *)
         test -e "$1" || help "$1" "no such file, directory or invalid command"
-        test -d "$1" || file "$1" || die "$1" "invalid .bats or .shts extension"
-        directory "$1" || die "$1" "no .bats or .shts tests found in directory"
+        test -d "$1" || { file "$1" && shift && continue; } || die "${1}:" "invalid .bats or .shts extension"
+        directory "$1" || die "${1}:" "no .bats or .shts tests found in directory"
         ;;
     esac
     shift
   done
 
-  [ ! "${no_parallelize_across_files-}" ] || [ "${jobs-}" ] || jobs=(-j 2)
-  [ ! "${no_parallelize_within_files-}" ] || [ "${jobs-}" ] || jobs=(-j 2)
-  ! $one || { jobs=(); no_parallelize_across_files=(); no_parallelize_within_files=(); }
+  [ ! "${no_parallelize_across_files-}" ] || [ "${jobs-}" ] || jobs=(--jobs 2)
+  [ ! "${no_parallelize_within_files-}" ] || [ "${jobs-}" ] || jobs=(--jobs 2)
+
+  ! $one || { jobs=(--jobs 1); no_parallelize_across_files=(); no_parallelize_within_files=(); }
 
   if $verbose; then
-    $gather_test_outputs_in ||{ gather_test_outputs_in=true; options+=("--gather-test-outputs-in" "${output_dir[@]}"); }
+    $gather_test_outputs_in ||{ gather_test_outputs_in=true; options+=("--gather-test-outputs-in" "${gather_dir[@]}"); }
     $no_tempdir_cleanup || options+=("--no-tempdir-cleanup")
     $output || { output=true; options+=("--output" "${output_dir[@]}"); }
     $show_output_of_passing_tests || options+=("--show-output-of-passing-tests")
@@ -192,16 +203,12 @@ main() {
     $verbose_run || options+=("--verbose-run")
   fi
 
-  if { $gather_test_outputs_in || $output; } && test -d "${outputs}"; then
-    rm -rf "${outputs}"
-    mkdir "${outputs}"
+  if ! $dry; then
+    ! $gather_test_outputs_in || ! test -d "${gather_dir[@]}" || rm -rf "${gather_dir[@]}"
+    ! $output || { rm -rf "${output_dir[@]}"; mkdir -p "${output_dir[@]}"; }
   fi
 
-  ! $gather_test_outputs_in || ! test -d "${gather_dir[@]}" || rm -rf "${gather_dir[@]}"
-  ! $output || { rm -rf "${output_dir[@]}"; mkdir "${output_dir[@]}"; }
-
-
-  if [ ! "${SHTS_TESTS-}" ] && ! tests "$(pwd)"; then
+  if [ ! "${SHTS_TESTS-}" ] && ! directory "$(pwd)"; then
     if [ "${SHTS_TOP-}" ]; then
       for i in __tests__ test test; do
         directory="${SHTS_TOP}/${i}"
@@ -213,9 +220,6 @@ main() {
     fi
   fi
 
-  SHTS_GATHER="${gather_dir[*]}"
-  SHTS_OUTPUT="${output_dir[*]}"
-
   local directories=()
   for i in "${SHTS_TESTS[@]}"; do
     [ -d "${i}" ] || { directories+=("$(dirname "${i}")"); continue; }
@@ -224,8 +228,16 @@ main() {
   mapfile -t directories < <(printf '%s\n' "${directories[@]}" | sort -u)
   SHTS_TEST_DIR="$(find "${directories[@]}" -mindepth 0 -maxdepth 0 -type d -print -quit)"
 
-  SHTS_COMMAND=(
-    bats
+
+  local directory="${SHTS_TESTS[0]}"
+  for i in "${SHTS_TESTS[@]}"; do
+    directory="$(comm -12 <(tr "/" "\n" <<< "${i/\//}") \
+                          <(tr "/" "\n" <<< "${directory/\//}") | sed 's|^|/|g' | tr -d '\n')"
+  done
+  test -d "${directory}" || directory="$(dirname "${directory}")"
+
+  local command=(
+    "${bats}"
     "${jobs[@]}"
     "${no_parallelize_across_files[@]}"
     "${no_parallelize_within_files[@]}"
@@ -234,12 +246,16 @@ main() {
     "${SHTS_TESTS[@]}"
   )
 
+  SHTS_COMMAND="${command[*]}"
+  SHTS_GATHER="${gather_dir[*]}"
+  SHTS_OUTPUT="${output_dir[*]}"
+
   if $list; then
     printarr "${SHTS_TESTS[@]}" | sed "s|$(pwd)/||"
   elif $dry; then
-    echo SHTS_GATHER="${SHTS_GATHER}" SHTS_OUTPUT="${SHTS_OUTPUT}" SHTS_TEST_DIR="${SHTS_TEST_DIR}" "${SHTS_COMMAND[@]}"
+    echo SHTS_GATHER="${SHTS_GATHER}" SHTS_OUTPUT="${SHTS_OUTPUT}" SHTS_TEST_DIR="${directory}" "${command[@]}"
   else
-    SHTS_GATHER="${SHTS_GATHER}" SHTS_OUTPUT="${SHTS_OUTPUT}" SHTS_TEST_DIR="${SHTS_TEST_DIR}" "${SHTS_COMMAND[@]}"
+    SHTS_TEST_DIR="${directory}" "${command[@]}"
   fi
 
   if $verbose; then
